# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f589efe9ef92f34729e1a6e478468d74f27711d4689afd00ddf37ce31eb73b58f97fe63cc59d4957d910e5b4799153c2705ec36718c42c2cb9f7f5abbf143e34

test:
  secret_key_base: 68ff927f379066dd73f5fbc44ffeb14cb174a1dbd217bc4c616f7fdf2e02669664d8b4a034c49b0d91059b0931aa0f8faa4752620566446c38b78c0ffca724f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
